<?php /** @package Promokodiki_Admitad */ ?>
<div class="wrap"><h1><?php esc_html_e( 'Магазины без связи', 'promokodiki-admitad' ); ?></h1><?php if ( $notice ) : ?><div class="notice notice-info"><p><?php echo esc_html( $notice ); ?></p></div><?php endif; ?>
<div class="card"><h2><?php esc_html_e( 'Партнёрские ссылки Admitad', 'promokodiki-admitad' ); ?></h2><p><?php esc_html_e( 'Сначала выполните предварительный просмотр. Генерация идёт ограниченными фоновыми пакетами и не обращается к API при открытии публичной страницы.', 'promokodiki-admitad' ); ?></p><form method="post"><?php wp_nonce_field( 'promokodiki_admitad_deeplink_batch', 'deeplink_nonce' ); ?><button class="button" name="deeplink_action" value="preview"><?php esc_html_e( 'Предварительный просмотр', 'promokodiki-admitad' ); ?></button> <button class="button button-primary" name="deeplink_action" value="enqueue"><?php esc_html_e( 'Поставить в очередь', 'promokodiki-admitad' ); ?></button></form><?php if ( is_array( $deeplink_preview ) ) : ?><p><?php printf( esc_html__( 'Создать: %1$d; обновить: %2$d; без изменений: %3$d; не поддерживается: %4$d; некорректно: %5$d.', 'promokodiki-admitad' ), (int) $deeplink_preview['create'], (int) $deeplink_preview['update'], (int) $deeplink_preview['unchanged'], (int) $deeplink_preview['unsupported'], (int) $deeplink_preview['invalid'] ); ?></p><?php endif; ?></div>
<form method="get"><input type="hidden" name="post_type" value="promocode"><input type="hidden" name="page" value="admitad-unlinked-shops"><label for="unlinked-shop-search"><?php esc_html_e( 'Поиск магазина', 'promokodiki-admitad' ); ?></label> <input id="unlinked-shop-search" name="s" value="<?php echo esc_attr( sanitize_text_field( wp_unslash( $_GET['s'] ?? '' ) ) ); ?>"><button class="button"><?php esc_html_e( 'Найти', 'promokodiki-admitad' ); ?></button></form>
<table class="widefat striped"><thead><tr><th><?php esc_html_e( 'Магазин', 'promokodiki-admitad' ); ?></th><th><?php esc_html_e( 'Причина', 'promokodiki-admitad' ); ?></th><th>Campaign ID</th><th><?php esc_html_e( 'Действия', 'promokodiki-admitad' ); ?></th></tr></thead><tbody>
<?php if ( ! $data['items'] ) : ?><tr><td colspan="4"><?php esc_html_e( 'Все существующие магазины связаны.', 'promokodiki-admitad' ); ?></td></tr><?php endif; ?>
<?php $reason_labels = array( 'missing' => 'Campaign ID не указан', 'invalid' => 'Campaign ID некорректен', 'unknown' => 'Кампании нет в локальном справочнике', 'duplicate' => 'Campaign ID используется несколько раз' ); ?>
<?php foreach ( $data['items'] as $item ) : ?><tr><td><?php echo esc_html( $item['name'] ); ?></td><td><?php echo esc_html( $reason_labels[ $item['reason'] ] ?? $item['reason'] ); ?></td><td><form method="post"><?php wp_nonce_field( 'promokodiki_admitad_shop_link', 'shop_link_nonce' ); ?><input type="hidden" name="term_id" value="<?php echo esc_attr( (string) $item['term_id'] ); ?>"><input type="number" min="1" name="campaign_id" value="<?php echo esc_attr( $item['campaign_id'] ); ?>" required><button class="button button-primary"><?php esc_html_e( 'Связать', 'promokodiki-admitad' ); ?></button></form><a href="<?php echo esc_url( admin_url( 'edit.php?post_type=promocode&page=admitad-companies&s=' . rawurlencode( $item['name'] ) ) ); ?>"><?php esc_html_e( 'Найти кампанию по названию', 'promokodiki-admitad' ); ?></a></td><td><a class="button" href="<?php echo esc_url( $item['edit_url'] ); ?>"><?php esc_html_e( 'Редактировать магазин', 'promokodiki-admitad' ); ?></a></td></tr><?php endforeach; ?>
</tbody></table></div>
