<?php $pages = max( 1, (int) ceil( $rows['total'] / $rows['per_page'] ) ); ?>
<table class="widefat striped"><thead><tr><th>Купон</th><th>Компания / рубрики</th><th>Причина / уверенность</th><th>Доказательства</th><th>Дата</th><th>Действия</th></tr></thead><tbody>
<?php if ( empty( $rows['items'] ) ) : ?><tr><td colspan="6">Случаи не найдены.</td></tr><?php endif; ?>
<?php foreach ( $rows['items'] as $row ) : $status = Promokodiki_Admitad_Admin_Presenter::status( 'review', $row['status'] ); ?>
<tr><td><?php if ( $row['view_url'] ) : ?><a href="<?php echo esc_url( $row['view_url'] ); ?>"><?php echo esc_html( $row['title'] ); ?></a><?php else : ?><?php echo esc_html( $row['entity_type'] . ':' . $row['entity_id'] ); ?><?php endif; ?><br><small>ID: <?php echo esc_html( $row['entity_id'] ); ?></small></td><td><?php echo esc_html( $row['company'] ); ?><br><?php echo esc_html( $row['term_paths'] ); ?></td><td><?php echo esc_html( $row['reason_code'] ); ?><br><span class="<?php echo esc_attr( $status['class'] ); ?>"><?php echo esc_html( $status['label'] ); ?></span> <?php echo esc_html( $row['confidence'] ); ?></td><td><details><summary>Показать</summary><pre><?php echo esc_html( wp_json_encode( $row['evidence'], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT ) ); ?></pre></details></td><td><?php echo esc_html( $row['created_at'] ); ?></td><td>
<?php if ( $row['edit_url'] ) : ?><a class="button" href="<?php echo esc_url( $row['edit_url'] ); ?>">Редактировать</a><?php endif; ?>
<?php if ( 'open' === $row['status'] && 'coupon' === $row['entity_type'] ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" data-admitad-ajax data-admitad-action="promokodiki_admitad_admin" data-admitad-operation="review_resolve_coupon" data-admitad-page="admitad-review" data-admitad-fragment="review-table"><input type="hidden" name="action" value="promokodiki_admitad_mapping_action"><input type="hidden" name="operation" value="resolve_coupon_only"><input type="hidden" name="queue_id" value="<?php echo esc_attr( (string) $row['id'] ); ?>"><?php wp_nonce_field( 'promokodiki_admitad_mapping_action' ); ?><label>Рубрики <select name="term_ids[]" multiple required size="3"><?php foreach ( $term_options as $term ) : ?><option value="<?php echo esc_attr( (string) $term['id'] ); ?>"><?php echo esc_html( $term['label'] ); ?></option><?php endforeach; ?></select></label><button class="button button-primary">Назначить и заблокировать</button></form><?php endif; ?>
<?php if ( 'open' === $row['status'] ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" data-admitad-ajax data-admitad-action="promokodiki_admitad_admin" data-admitad-operation="review_archive" data-admitad-page="admitad-review" data-admitad-fragment="review-table"><input type="hidden" name="action" value="promokodiki_admitad_mapping_action"><input type="hidden" name="operation" value="archive_review_case"><input type="hidden" name="queue_id" value="<?php echo esc_attr( (string) $row['id'] ); ?>"><?php wp_nonce_field( 'promokodiki_admitad_mapping_action' ); ?><button class="button">Архивировать</button></form><?php endif; ?>
</td></tr><?php endforeach; ?></tbody></table>
<?php if ( $pages > 1 ) : ?><nav><?php for ( $i = 1; $i <= $pages; ++$i ) : ?><a href="<?php echo esc_url( add_query_arg( 'paged', $i, $request->url() ) ); ?>" data-admitad-ajax data-admitad-action="promokodiki_admitad_admin" data-admitad-operation="review_list" data-admitad-page="admitad-review" data-admitad-fragment="review-table"><?php echo esc_html( (string) $i ); ?></a> <?php endfor; ?></nav><?php endif; ?>
